ridc:
  client:
    url: http://localhost:16300/urm/idcplg
    http-library: apache4
  context:
    user: urmproxy
    password: 
    time-zone: "America/Bogota"
  owcc11g:
    client:
      url: http://localhost:16300/urm/idcplg
      http-library: apache4
    context:
      user: urmadmin
      password: 
      time-zone: "America/Bogota"
